FROM rust:slim

RUN useradd --create-home appuser

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY tests ./tests

RUN chown -R appuser:appuser /app

USER appuser

CMD ["cargo", "test"]
